; Define our MPLAB shortcuts, constants etc

; These are set for 16F1827

;RLEDPORT 	equ PORTB
;RLED 		equ 0
;GLEDPORT 	equ PORTB
;GLED 		equ 1
;BLEDPORT 	equ PORTB
;BLED 		equ 3
;SPEED 		equ d'30'

DS1PORT 	equ PORTA
DS1 		equ 2
DS2PORT 	equ PORTA
DS2 		equ 5
DS3PORT 	equ PORTB
DS3 		equ 0
DS4PORT 	equ PORTB
DS4 		equ 1
DS5PORT 	equ PORTB
DS5 		equ 4

;PWMR		equ	CCPR3L
;PWMG		equ	CCPR4L
;PWMB		equ	CCPR1L


;*********************
